stages:
  - check
  - build
  - build-ci-release-docker
  - kubernetes-config
  - kubernetes-deploy
  - pages
  - release-docker-production

image: docker.dev.dszn.cz/golang-build:stretch

.ci_scripts_image: &ci_scripts_image
  image: docker.dev.dszn.cz/generic/ci-scripts:1

variables:
  DOCKER_NAMESPACE: sklik-devops
  KUBERNETES_NAMESPACE: sklik-devops-sandbox

lint:
  stage: check
  script: |
    make lint

test:
  stage: check
  script: |
    make test-and-coverage
  artifacts:
    paths:
      - coverage.out
    expire_in: 1 week

test-tag-version:
  <<: *ci_scripts_image
  stage: check
  script: |
    /ci/test-version-match.sh
  only:
    - /^v[0-9]+\.[0-9]+\.[0-9]+/


build:
  stage: build
  script: |
    make build
  artifacts:
    paths:
      - slo_exporter
    expire_in: 1 week

build-ci-release-docker:
  <<: *ci_scripts_image
  stage: build-ci-release-docker
  script: |
    /ci/docker-build.sh --namespace $DOCKER_NAMESPACE
    /ci/docker-release-ci.sh --namespace $DOCKER_NAMESPACE --extra-tags "$CI_COMMIT_REF_NAME"
  dependencies:
    - build
  artifacts:
    expire_in: 1 mos
    paths:
      - docker-release-ci.uri

# kubernetes configuration
# ---------------------------------------------------------------------------
.kubernetes-config: &kubernetes-config
  <<: *ci_scripts_image
  stage: kubernetes-config
  environment:
    name: kubernetes-config
  script: |
    /ci/kubernetes-ci-init.sh
    for i_slo_exporter_instance in skweb{1,2}-{ko,ng}; do
      /ci/kubernetes-config-custom.sh --app slo-exporter-userportal-${i_slo_exporter_instance} --destination-dir kubernetes/${ENVIRONMENT}-slo-exporter-userportal-${i_slo_exporter_instance} --env-file conf/${ENVIRONMENT}-userportal.env --env-file conf/${i_slo_exporter_instance}.include.env --no-configmap
    done
  artifacts:
    expire_in: 3 mo
    name: kubernetes-config
    paths:
      - ./kubernetes/${ENVIRONMENT}*/*.yaml

kubernetes-development-config:
  <<: *kubernetes-config
  variables:
    ENVIRONMENT: development
  before_script:
    - export DOCKER_IMAGE=$(cat docker-release.uri docker-release-ci.uri 2>/dev/null | head -1)

kubernetes-production-config:
  <<: *kubernetes-config
  variables:
    ENVIRONMENT: production
  before_script:
    - export DOCKER_IMAGE=$(/ci/production-docker-image-name.sh "$(cat docker-release.uri docker-release-ci.uri 2>/dev/null | head -1)")


kubernetes-deploy:
  <<: *ci_scripts_image
  stage: kubernetes-deploy
  variables:
    ENVIRONMENT: development
  environment:
    name: tt-k8s1.ko
  script: |
    /ci/kubernetes-ci-init.sh
    for i_env in ${ENVIRONMENT}-slo-exporter-userportal-skweb{1,2}-{ko,ng}; do
      /ci/kubernetes-deploy.sh --namespace "${KUBERNETES_NAMESPACE}" --env "${i_env}"
    done
  dependencies:
    - kubernetes-development-config
  only:
    - master
    - /^v[0-9]+\.[0-9]+\.[0-9]+/

pages:
  stage: pages
  dependencies:
    - test
  only:
    - master
  script: |
    mkdir public
    go tool cover -html coverage.out -o public/index.html
  artifacts:
    expire_in: 1 mos
    paths:
      - public


# Release docker image to production registry
# ---------------------------------------------------------------------------
release-docker-production:
  stage: release-docker-production
  except:
    - branches
  only:
    - /^v[0-9]+\.[0-9]+\.[0-9]+/
  script: |
    /ci/docker-release-to-production-registry-dirt.sh --docker-image-name-file docker-release.uri --docker-image-digest-file docker-release.digest
