version: '3'

# To make this work, add to the root of this repository .env file with credentials such as:
# SZN_LOGY_USER=...
# SZN_LOGY_PASSWORD=...

services:
  tail:
    image: docker.dev.dszn.cz/generic/ci-scripts:latest
    environment:
      SZN_LOGY_USER: "${SZN_LOGY_USER}"
      SZN_LOGY_PASSWORD: "${SZN_LOGY_PASSWORD}"
    entrypoint: ["bash"]
    command:
      - "-c"
      - "cd /tmp/szn-logy/; /scripts/http_tail.sh"
    volumes:
      - ./scripts:/scripts
      - log-volume:/tmp/szn-logy
    depends_on:
      - slo-exporter

  slo-exporter:
    image: docker.dev.dszn.cz/generic/ci-scripts:latest
    ports:
      - 8080:8080
    entrypoint: ["/slo-exporter/slo_exporter"]
    command:
      - "--follow"
      - "--log-level=debug"
      - "/tmp/szn-logy/access_log"
    volumes:
      - ./:/slo-exporter
      - log-volume:/tmp/szn-logy

  prometheus:
    image: prom/prometheus:latest
    ports:
      - 9090:9090
    environment:
      PROMETHEUS_CONFIG: |
        {"scrape_configs":[{
            "job_name": "slo-exporter",
            "scrape_interval": "2s",
            "static_configs":[
              {"targets":["slo-exporter:8080"]},
              ],
            }]
        }
    entrypoint: ["sh"]
    command:
      - "-c"
      - 'echo $PROMETHEUS_CONFIG; echo $$PROMETHEUS_CONFIG > /etc/prometheus/prometheus.yml; cat /etc/prometheus/prometheus.yml; prometheus --config.file=/etc/prometheus/prometheus.yml'


volumes:
  log-volume:
