version: '3'

# To make this work, add to the root of this repository .env file with credentials such as:
# SZN_LOGY_USER=...
# SZN_LOGY_PASSWORD=...

services:
  tail-szn-logy:
    image: docker.dev.dszn.cz/generic/ci-scripts:latest
    entrypoint: ["bash"]
    command:
      - "-c"
      - "cd /tmp/szn-logy/; while true; do wget --no-check-certificate -c -o /dev/null --http-user=${SZN_LOGY_USER} --password=${SZN_LOGY_PASSWORD} https://skweb1.ko.seznam.cz:8888/szn-sklik-userproxy/access_log; sleep 2; done"
    volumes:
      - log-volume:/tmp/szn-logy
    depends_on:
      - slo-exporter

  slo-exporter:
    build: .
    ports:
      - 8080:8080
    command:
      - "--follow"
      - "/tmp/szn-logy/access_log"
    volumes:
      - log-volume:/tmp/szn-logy

  prometheus:
    image: prom/prometheus:latest
    ports:
      - 9090:9090
    environment:
      PROMETHEUS_CONFIG: |
        {"scrape_configs":[{
            "job_name": "slo-exporter",
            "scrape_interval": "2s",
            "static_configs":[
              {"targets":["slo-exporter:8080"]},
              ],
            }]
        }
    entrypoint: ["sh"]
    command:
      - "-c"
      - 'echo $PROMETHEUS_CONFIG; echo $$PROMETHEUS_CONFIG > /etc/prometheus/prometheus.yml; cat /etc/prometheus/prometheus.yml; prometheus --config.file=/etc/prometheus/prometheus.yml'


volumes:
  log-volume:
