defaults: &defaults
  docker:
    - image: circleci/golang:1.14
  resource_class: small

version: 2
jobs:
  lint:
    <<: *defaults
    steps:
      - checkout
      - run: make lint

  test:
    <<: *defaults
    steps:
      - checkout
      - run: make test-and-coverage

  build:
    <<: *defaults
    steps:
      - checkout
      - run: make build SLO_EXPORTER_VERSION=${CIRCLE_TAG:-$CIRCLE_SHA1}
      - persist_to_workspace:
          root: .
          paths:
            - build

  build_docker:
    <<: *defaults
    steps:
      - checkout
      - setup_remote_docker:
          version: 17.07.0-ce
      - attach_workspace:
          at: .
      - run: cp build/linux-amd64/slo_exporter ./slo_exporter
      - run: make docker-build

  build_docker_release:
    <<: *defaults
    environment:
      DOCKERHUB_USERNAME=sklikdevops
    steps:
      - checkout
      - setup_remote_docker:
          version: 17.07.0-ce
      - attach_workspace:
          at: .
      - run:
          command: |
            cp build/linux-amd64/slo_exporter ./slo_exporter
            echo "${DOCKERHUB_PASSWORD}" | docker login -u="${DOCKERHUB_USERNAME}" --password-stdin
            export SLO_EXPORTER_VERSION=${CIRCLE_TAG:-$CIRCLE_SHA1}
            make docker-build
            make docker-push

  github_release:
    <<: *defaults
    steps:
      - checkout
      - attach_workspace:
          at: .
      - run:
          command: |
            export SLO_EXPORTER_VERSION=${CIRCLE_TAG:-$CIRCLE_SHA1}
            make github-release

workflows:
  version: 2
  slo-exporter:
    jobs:
      - lint
      - test
      - build:
          filters:
            tags:
              only: /^v[0-9]+(\.[0-9]+){2}(-.+|[^-.]*)$/
      - build_docker:
          requires:
            - build
          filters:
            tags:
              ignore: /^v[0-9]+(\.[0-9]+){2}(-.+|[^-.]*)$/
      - build_docker_release:
          requires:
            - build
          filters:
            tags:
              only: /^v[0-9]+(\.[0-9]+){2}(-.+|[^-.]*)$/
            branches:
              ignore: /.*/
      - github_release:
          requires:
            - build
          filters:
            tags:
              only: /^v[0-9]+(\.[0-9]+){2}(-.+|[^-.]*)$/
            branches:
              ignore: /.*/
