rules:
  - metadata_matcher:
      - operator: isMatchingRegexp
        key: statusCode
        value: ".+"
    slo_matcher:
      domain: test-app
    failure_conditions:
      - operator: numberIsHigherThan
        key: statusCode
        value: 499
    additional_metadata:
      slo_type: availability
      slo_version: 6

  - metadata_matcher:
      - operator: isMatchingRegexp
        key: le
        value: ".+"
    slo_matcher:
      domain: test-domain
    failure_conditions:
      - operator: numberIsHigherThan
        key: minValue
        value: 0.2
    additional_metadata:
      slo_type: latency
      slo_version: 6
